xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryServices categoryTryServices;

        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryServices = new CategoryTryServices(db);
        }

        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryServices.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryServices.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }
        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryServices.Edit(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            respon.Entity = dataView;
            return View(respon.Entity);

        }
        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }
        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryServices.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryTryServices.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }
            return View(respon.Entity);
        }
    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "Create Category Try";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Create" method="post">
          <div class="mb-4 row a">
            <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
              <span asp-validation-for="NameCategory" class="text-danger"></span>
            </div>
          </div>

          <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
            </div>
          </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    //Layout = null;
    ViewData["Title"] = "Delete Category Try";

}

<div class="card">
    <div class="card-body">
        <div class="h6 mb-4">@ViewData["Title"]</div>
        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h4>Are you Sure for delete @Model.NameCategory ?</h4>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back To List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Detail Category Try";
}

<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        
          <div class="mb-4 row a">
            <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
              
            </div>
          </div>

          <div class="mb-4 row">
            <label for="Description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              
              <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
            </div>
          </div>
        

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    //Layout = null;
    ViewData["Title"] = "Edit Category Try";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Edit" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
          <div class="mb-4 row a">
            <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
              <span asp-validation-for="NameCategory" class="text-danger"></span>
            </div>
          </div>

          <div class="mb-4 row">
            <label for="Description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back To List</a>
            </div>
          </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels
@{
    ViewData["Title"] = "Category Try";
}

<div class="card">
    <div class="card-body">
        <h1 class="card-title">@ViewData["Title"]</h1>

        @*<div class="mb-2 row">
            <form asp-action="Index" method="get" id="form_search">
                <div class="col-12">
                    <div class="customize-input float-right">
                        <div class="input-group">
                            <input type="text" class="form-control" name="searchString" value="@ViewBag.currentFilter" placeholder="Search.."/>
                            <div class="input-group-prepend">
                                <button type="button" class="btn btn-primary" id="btn_search">
                                    <i class="bi bi-search"></i>
                                </button>

                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>*@

        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Name Category</th>
              <th scope="col">Description</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
                @foreach(VMTblCategory item in Model)
                {
                     <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.NameCategory</td>
                        <td>@item.Description</td>
                        <td>
                            <button type="button" class="btn btn-outline-dark btn_edit" data-id="@item.Id">Edit</button>
                            <button type="button" class="btn btn-outline-dark btn_detail" data-id="@item.Id">Detail</button>
                            <button type="button" class="btn btn-outline-dark btn_delete" data-id="@item.Id">Delete</button>

                        </td>
                    </tr>
                }
       

          </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#btn_create").click(function(){
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Create")
            $("#myModal").modal("show")
            
        })
        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Edit?id=" + id)
            $("#myModal").modal("show")
        })
         $(".btn_detail").click(function(){
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Detail?id=" + id)
            $("#myModal").modal("show")
        })

        $(".btn_delete").click(function(){
            var id = $(this).data("id")
            $("#myModal_body").empty()
            $("#myModal_body").load("/CategoryTry/Delete?id=" + id)
            $("#myModal").modal("show")
        })
        
    })
</script>