xpos314/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantController : Controller
    {
        private CategoryServices categoryServices;
        private VariantServices variantServices;
        private int IdUser = 1;


        public VariantController(CategoryServices _categoryServices, VariantServices _variantServices)
        {
            this.categoryServices = _categoryServices;
            this.variantServices = _variantServices;

            //this.configuration = _configuration;
            //this.categoryServices = new CategoryServices(this.configuration);
            //this.variantServices = new VariantServices(this.configuration);
        }

        public async Task<IActionResult> Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber,
                                               int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;

            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantServices.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                || a.NameCategory.ToLower().Contains(searchString.ToLower())
                || a.Description.ToLower().Contains(searchString.ToLower()) 
                
                ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> listCategory = await categoryServices.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
        {
           
            VMResponse respon = await variantServices.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });

            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantServices.GetDataById(id);

            List<TblCategory> listCategory = await categoryServices.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantServices.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantServices.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantServices.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {

            VMResponse respon = await variantServices.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
    }
}

xpos314/xpos314.web/Views/Variant/Create.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    ViewData["Title"] = "Create Variant";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Create" method="post" id="form_input">
          <div class="mb-4 row a">
            <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
              
            </div>
          </div>

		  <div class="mb-4 row">
            <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
              @Html.DropDownList("IdCategory", 
              new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
              "--Pilih Kategori--", 
              new { @class= "form-control" }
              )
            </div>
          </div>

          <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back To List</a>
            </div>
          </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5,
			},
			IdCategory: "required",
		},
		messages: {
			NameVariant: {
				required: "Please fill name Variant!",
				minlength: "The Name must consist of at least 5 character!",
			},
			IdCategory: "Plese Select Category",
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			

			$.ajax({
				url: "/Variant/Create",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$(".modal").modal("hide")

						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else {
						//Toast.fire({
						//    icon: "Failed",
						//    title: data.message
						//})
						toastr.error(data.message)
					}
				}
			})
		}
	})
</script>

xpos314/xpos314.web/Views/Variant/Delete.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    ViewData["Title"] = "Delete Variant";

}

<div class="card">
    <div class="card-body">
        <div class="h6 mb-4">@ViewData["Title"]</div>
        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h4>Are you Sure for delete @Model.NameVariant ?</h4>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back To List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/Variant/Detail.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    ViewData["Title"] = "Create Variant";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        
          <div class="mb-4 row a">
            <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
              
            </div>
          </div>

          <div class="mb-4 row a">
            <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="IdCategory" name="IdCategory" value="@Model.NameCategory" readonly>
              
            </div>
          </div>

		  

          <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back To List</a>
            </div>
          </div>
       

    </div>
</div>

xpos314/xpos314.web/Views/Variant/Edit.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@model VMTblVariant
@{
    //Layout = null;
    ViewData["Title"] = "Edit Variant";

}
<div class="card">
    <div class="card-body">
        <h2 class="display-6">@ViewData["Title"]</h2>


        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
          <div class="mb-4 row a">
            <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
              <span id="validate_NameVariant" class="text-danger"></span>
            </div>
          </div>

		   <div class="mb-4 row">
            <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
              @Html.DropDownList("IdCategory", 
              new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
              "--Pilih Kategori--", 
              new { @class= "form-control" }
              )
            </div>
          </div>

          <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
              <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
            </div>
          </div>
 
          <div class="mb-4 row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Submit</button>
              <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back To List</a>
            </div>
          </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
		errorClass: "is-invalid text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5,
			},
			IdCategory: "required",
		},
		messages: {
			NameVariant: {
				required: "Please fill name Variant!",
				minlength: "The Name must consist of at least 5 character!",
			},
			IdCategory: "Plese Select Category",
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize();
			

			$.ajax({
				url: "/Variant/Edit",
				type: "POST",
				dataType: "json",
				data: dataForm,
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$(".modal").modal("hide")

						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					}
					else {
						//Toast.fire({
						//    icon: "Failed",
						//    title: data.message
						//})
						toastr.error(data.message)
					}
				}
			})
		}
	})
</script>

xpos314/xpos314.web/Views/Variant/Index.cshtml
@using System.Globalization
@using xpos314.datamodels
@using xpos314.viewmodels
@model PaginatedList<VMTblVariant>

@{
    //Layout = null;
    ViewData["Title"] = "Variant";

}



<div class="card">
    <div class="card-header">

         <div class="row mb-3">
               <div class="col-12">
                   <div class="card-title">@ViewData["Title"]</div>
                   <div class="d-flex justify-content-between">
                        <button type="button" id="btn_create" class="btn btn-outline-dark">Create</button>
                       
                            <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                                <div class="input-group w-100">
                                    <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search">

                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default" title="search">
                                            <i class="fas fa-search"></i>
                                        </button>

                                        <a class="btn btn-default" asp-action="Index" title="reset">
                                            <i class="fas fa-redo"></i>
                                        </a>
                                    </div>
                                </div>
                            </form>
                    </div>
                </div>
         </div>
       
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>
                                Name Variant
                            </a>
                        </th>
                        <th>Name Category</th>
                        <th>Description</th>
                        <th>Is Delete</th>
                        <th>Create Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (VMTblVariant item in Model)
                        {
                            <tr>
                                <td>@item.NameVariant</td>
                                <td>@item.NameCategory</td>
                                <td>@item.Description</td>
                                <td>
                                    @if(@item.IsDelete == true)
                                    {
                                        <input type="checkbox" checked disabled/>
                                    }
                                    else
                                    {
                                        <input type="checkbox" disabled />
                                    }
                                </td>
                                <td>
                                    @item.CreateDate.ToString("dddd, dd MM yyyy HH:mm:ss", new CultureInfo("id-ID"))
                                </td>

                                <td>
                                    <button type="button" class="btn btn-outline-dark btn_edit" dataid="@item.Id">
                                        Edit
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_detail" dataid="@item.Id">
                                        Detail
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_delete" dataid="@item.Id" >
                                       Delete
                                    </button>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">

                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </form>
                </div>
                <div class="col-10">
                    Page @Model.PageIndex of @Model.TotalPages
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="mr-2 btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){

        

        $("#btn_create").click(function(){
            $("#myModal_body").empty();
            $("#myModal_body").load("/Variant/Create")
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function(){

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Variant/Detail?id="+id)
            $("#myModal").modal("show");
        });

        $(".btn_edit").click(function(){

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Variant/Edit?id="+id)
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function(){
            var id = $(this).attr("dataid");
            $("#myModal_body").empty();
            $("#myModal_body").load("/Variant/Delete?id="+id)
            $("#myModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function(){
            $("#form_pagesize").submit();
        })

    });
</script>